import Gallery from '@/components/gallery';
import Head from 'next/head'
import Link from "next/link";
import {useState} from 'react';
import styles from "./../styles/Home.module.scss";

import Confetti from 'react-confetti'

export default function Home() {
  const [confettiPieces, setConfettiPieces] = useState(200);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.Home}>
        <Confetti
        width={2000}
        height={700}
        numberOfPieces={confettiPieces}
        
        />
        <label htmlFor="confetti-pieces"></label>
        <input
          type="range"
          name="confetti-pieces"
          id="confetti-pieces"
          onInput={(e) => setConfettiPieces(e.target.value) * 3}
        />
        <h1>Home</h1>
        <Gallery />
        <div className={styles.linkUsers} >
          <Link href="/users">Users</Link>
        </div>
      </div>
    </>
  )
}
